[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tortuepin/tolog_new'
build = 'make install'
on_ft = 'markdown'

[[plugins]]
repo = 'tortuepin/tolog_deoplete_source'
on_ft = 'markdown'

[[plugins]]
repo = 'tortuepin/tolog.nvim'
build = 'make'
on_ft = 'markdown'

[[plugins]]
repo = 'tomasr/molokai'

