## tolog
[[plugins]]
repo = 'tortuepin/tolog_new'
build = 'make install'
on_ft = 'markdown'

[[plugins]]
repo = 'tortuepin/tolog_deoplete_source'
on_ft = 'markdown'

[[plugins]]
repo = 'tortuepin/tolog.nvim'
build = 'make'
on_ft = 'markdown'


## lsp関連
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

### ddc
#[[plugins]]
#repo = 'vim-denops/denops.vim'
#
#[[plugins]]
#repo = 'Shougo/ddc.vim'
#
#[[plugins]]
#repo = 'shun/ddc-vim-lsp'
#
#[[plugins]]
#repo = 'Shougo/ddc-around'



## colorscheme
[[plugins]]
repo = 'tomasr/molokai'


## 他
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'thinca/vim-quickrun'

