## tolog
[[plugins]]
repo = 'tortuepin/tolog_new'
build = 'make install'
on_ft = 'markdown'

# it's not work without setting.
# it's bother for me.
#[[plugins]]
#repo = 'tortuepin/tolog_deoplete_source'
#on_ft = 'markdown'

[[plugins]]
repo = 'tortuepin/tolog.nvim'
build = 'make install'
on_ft = 'markdown'

[[plugins]]
repo = 'tortuepin/workflowish'
on_ft = 'wofl'

## lsp関連
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#
#[[plugins]]
#repo = 'lighttiger2505/deoplete-vim-lsp'

## ddc
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

## ddu
[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-source-register'

[[plugins]]
repo = 'kuuote/ddu-source-mr'

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'


## colorscheme
[[plugins]]
repo = 'tomasr/molokai'


## 他
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    let g:netrw_nogx = 1
    nmap gx <Plug>(openbrowser-smart-search)
    vmap gx <Plug>(openbrowser-smart-search)
'''
